apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-consumer-job
spec:
  template:
    spec:
      containers:
      - name: kafka-consumer
        image: python:3.9-slim
        command: ["python", "/app/kafka_consumer_ml.py"]
        env:
        - name: KAFKA_BROKER
          value: "localhost:9092"
        - name: KAFKA_TOPIC
          value: "defillama_apy"
        volumeMounts:
        - name: scripts
          mountPath: /app
      restartPolicy: Never
      volumes:
      - name: scripts
        hostPath:
          path: /mnt/data
