apiVersion: batch/v1
kind: Job
metadata:
  name: producer
spec:
  template:
    metadata:
      labels:
        app: producer
    spec:
      restartPolicy: Never
      containers:
      - name: iot-producer
        image: 10.56.0.219:5000/producer1:latest
        env:
        - name: KAFKA_BROKER
          value: kafka:9092
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
