apiVersion: batch/v1
kind: Job
metadata:
  name: ml-training-job
spec:
  template:
    spec:
      containers:
        - name: ml-training
          image: 10.56.0.219:5000/training-ml:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "defillama_apy"
          volumeMounts:
            - name: model-storage
              mountPath: /mnt/data
      restartPolicy: OnFailure
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-pvc
